name = "Bangumis"
uuid = "ad8dfdfc-bf80-4d0a-b5f0-e1f877673ab7"
authors = ["pingline <pingline@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "17"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
