name: CodeCov

on:
  push:
    paths:
      - src/*

jobs:
  CodeCov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia --color=yes --project=. --code-coverage test/runtests.jl
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
