name: Run tests

on: [push, pull_request]

jobs:
  CodeCov:
    runs-on: ubuntu-latest
    step:
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
